apiVersion: apps/v1
kind: Deployment
metadata:
  name: bin-server
  namespace: default
  labels:
    app: bin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bin-server
  template:
    metadata:
      labels:
        app: bin-server
    spec:
      containers:
        - name: bin-server
          image: gitlab-hrp.ru:5050/sre/initial/bmax1977/kibanacloud:latest
          imagePullPolicy: Never
          ports:
            - name: bin-server
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: bin-server
