apiVersion: v1
kind: Service
metadata:
  name: bin-server
  namespace: default
spec:
  ports:
    - name: service
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: bin-server
  sessionAffinity: None
